#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_instance()
{
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command /sbin/ExtBoardD
	procd_close_instance
}

start_service()
{
	start_instance
}


